# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Ensure HAProxy cluster is defined
  assert:
    that: "{{ haproxy_cluster is defined }}"
    success_msg: "haproxy_cluster is configured as expected"
    fail_msg: "haproxy_cluster must be set to a cluster"

- name: Locate HAProxy cluster
  set_fact:
    _haproxy_cluster_matches: '{{ definition.clusters | find_clusters(haproxy_cluster)}}'

- name: Ensure HAProxy cluster exists
  assert:
    that: "{{ _haproxy_cluster_matches | length > 0 }}"
    success_msg: "Configured cluster {{ haproxy_cluster }} located successfully"
    fail_msg: "Configured cluster {{ haproxy_cluster }} does not exist"

- set_fact:
    _haproxy_cluster: "{{ _haproxy_cluster_matches | first }}"

- name: Ensure TLS is enabled for HAProxy cluster
  assert:
    that: "{{ _haproxy_cluster.security.tls | default(False) }}"
    success_msg: "TLS is enabled for proxied cluster as required"
    fail_msg: "TLS must be enabled to configure a cluster with HAProxy"

- name: Install HAProxy
  package:
    lock_timeout: 60
    name: haproxy
    state: latest

- name: Configure HAProxy
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy

- name: Enable HAProxy
  service:
    name: haproxy
    enabled: yes
    state: restarted
