# Copyright 2023 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Download MySQL Connector/J
  get_url:
    url: "{{ mysql_connector_url }}"
    dest: "{{ mysql_connector_download_dir }}/mysql-connector-java.zip"
    checksum: "{{ mysql_connector_checksum }}"
    mode: 0644
  become: no
  run_once: true
  delegate_to: localhost

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- name: Install unzip package
  ansible.builtin.package:
    lock_timeout: "{{ (ansible_os_family == 'RedHat') | ternary(60, omit) }}"
    name: unzip
    state: present

- name: Extract MySQL Connector/J zip file
  unarchive:
    src: "{{ mysql_connector_download_dir }}/mysql-connector-java.zip"
    dest: "{{ mysql_connector_extract_dir }}"
    exclude:
      - src

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "{{ mysql_connector_local_path }}"
    dest: /usr/share/java/mysql-connector-java.jar
    remote_src: yes
    mode: 0644

# MySql on rhel8 fix
- name: Fix MySQL on RHEL8
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "8"
  block:
    - name: Remove mariadb packages if needed
      package:
        name: mariadb-devel
        state: absent

    - name: Install mysql-devel package
      package:
        name: mysql-devel
        state: installed

    - name: Send my_config.h for RHEL 8
      template:
        src: my_config.h
        dest: /usr/include/mysql/my_config.h

## TODO Fix for RHEL8
    - name: Install Mysql packages for python - PyMySQL
      shell: /usr/local/bin/pip install PyMySQL --force-reinstall --ignore-installed
      ignore_errors: true

  
