---

- name: Load defaults
  when: deprecation_msg is defined
  run_once: true
  ansible.builtin.include_role:
    name: cloudera.cluster.cloudera_manager.common

- name: Deprecation warning
  when: deprecation_msg is defined
  run_once: true
  cloudera.cluster.warn:
    msg: "{{ deprecation_msg }}"

- name: Push TLS settings for Ranger KMS
  cloudera.cluster.cm_api:
    endpoint: "/clusters/{{ cluster_name | urlencode() }}/services/{{ kms_service_name | lower }}/roleConfigGroups/{{ kms_service_name | lower }}-RANGER_KMS_SERVER_KTS-BASE/config"
    method: PUT
    body: "{{ lookup('file', 'kms_tls.json', errors='ignore' ) }}"
  ignore_errors: true
  when: cloudera_manager_version is version('7.0.0','>=')

- name: Push TLS settings for Keytrustee roleConfigGroups
  cloudera.cluster.cm_api:
    endpoint: "/clusters/{{ cluster_name | urlencode() }}/services/{{ kms_service_name | lower }}/roleConfigGroups/{{ kms_service_name | lower }}-KMS_KEYTRUSTEE-BASE/config"
    method: PUT
    body: "{{ lookup('file', 'kms_tls_cdh.json', errors='ignore' ) }}"
  ignore_errors: true
  when: cloudera_manager_version is version('7.0.0','<')

- name: Push TLS settings for Keytrustee config
  cloudera.cluster.cm_api:
    endpoint: "/clusters/{{ cluster_name | urlencode() }}/services/{{ kms_service_name | lower }}/config"
    method: PUT
    body: "{{ lookup('file', 'kms_tls_cdh_kms.json', errors='ignore' ) }}"
  ignore_errors: true
  when: cloudera_manager_version is version('7.0.0','<')

# Restart all clusters to be sure
- name: Find existing clusters
  cloudera.cluster.cm_api:
    endpoint: /clusters?clusterType=any
  register: clusters_response

- name: Restart clusters and redeploy configs
  include_role:
    name: cloudera.cluster.operations.restart_cluster
  vars:
    cluster_to_restart: "{{ __cluster_restart_item }}"
  loop: "{{ clusters_response.json | json_query('items[*].name') }}"
  loop_control:
    loop_var: __cluster_restart_item
