# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Set Cloudera Manager agent 'server_host' in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^server_host"
    line: "server_host={{ cloudera_manager_host }}"
  notify:
    - restart cloudera-scm-agent

- name: Set use_tls in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^use_tls"
    line: "use_tls=1"
  when: tls | default(False) or manual_tls_cert_distribution | default(False)
  notify:
    - restart cloudera-scm-agent

- name: Set verify_cert_file in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^(# )?verify_cert_file="
    line: "verify_cert_file={{ tls_chain_path }}"
  when: tls | default(False) or manual_tls_cert_distribution | default(False)
  notify:
    - restart cloudera-scm-agent

- name: Set client_key_file in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^(# )?client_key_file="
    line: "client_key_file={{ tls_key_path_generic }}"
  when: tls | default(False) or manual_tls_cert_distribution | default(False)
  notify:
    - restart cloudera-scm-agent

- name: Set client_keypw_file in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^(# )?client_keypw_file="
    line: "client_keypw_file={{ tls_key_password_file }}"
  when: tls | default(False) or manual_tls_cert_distribution | default(False)
  notify:
    - restart cloudera-scm-agent

- name: Set client_cert_file in config.ini
  lineinfile:
    dest: "{{ cloudera_manager_agent_config_file }}"
    regexp: "^(# )?client_cert_file="
    line: "client_cert_file={{ tls_cert_path_generic }}"
  when: tls | default(False) or manual_tls_cert_distribution | default(False)
  notify:
    - restart cloudera-scm-agent

- name: Restart Cloudera Manager agent if required
  meta: flush_handlers

- name: Ensure Cloudera Manager agent is started
  service:
    name: cloudera-scm-agent
    state: started
