---
role_mappings:
  ADLS_CONNECTOR:
  ATLAS:
    - ATLAS_SERVER
  AWS_S3:
  CDSW:
    - CDSW_APPLICATION
    - CDSW_DOCKER
    - CDSW_MASTER
    - CDSW_WORKER
  CORE_SETTINGS:
    - GATEWAY
    - STORAGEOPERATIONS
  CRUISE_CONTROL:
    - CRUISE_CONTROL_SERVER
  DAS:
    - DAS_EVENT_PROCESSOR
    - DAS_WEBAPP
  DATA_CONTEXT_CONNECTOR:
    - GATEWAY
  HBASE:
    - GATEWAY
    - HBASERESTSERVER
    - HBASETHRIFTSERVER
    - MASTER
    - REGIONSERVER
  HDFS:
    - BALANCER
    - DATANODE
    - FAILOVERCONTROLLER
    - GATEWAY
    - HTTPFS
    - JOURNALNODE
    - NAMENODE
    - NFSGATEWAY
    - SECONDARYNAMENODE
  HIVE:
    - GATEWAY
    - HIVEMETASTORE
    - HIVESERVER2
    - WEBHCAT
  HIVE_EXEC:
#   - TODO
  HIVE_LLAP: #confirm these
    - GATEWAY
    - HIVESERVER2
    - LLAPPROXY
  HIVE_ON_TEZ:
    - GATEWAY
    - HIVESERVER2
  HUE:
    - HUE_LOAD_BALANCER
    - HUE_SERVER
    - KT_RENEWER
  IMPALA:
    - CATALOGSERVER
    - IMPALAD
    - STATESTORE
  ISILON:
    - GATEWAY
  KMS:
    - KMS
  KAFKA:
    - GATEWAY
    - KAFKA_BROKER
    - KAFKA_CONNECT
    - KAFKA_MIRROR_MAKER
  KEYTRUSTEE:
    - KMS_KEYTRUSTEE
  KEYTRUSTEE_SERVER:
    - DB_ACTIVE
    - DB_PASSIVE
    - KEYTRUSTEE_ACTIVE_SERVER
    - KEYTRUSTEE_PASSIVE_SERVER
  KNOX:
    - IDBROKER
    - KNOX_GATEWAY
  KS_INDEXER:
    - HBASE_INDEXER
  KUDU:
    - KUDU_MASTER
    - KUDU_TSERVER
  LIVY:
    - GATEWAY
    - LIVY_SERVER
  LUNA_KMS:
    - HSMKP_LUNA
    - HSMKP_METASTORE_LUNA
  OOZIE:
    - OOZIE_SERVER
  OZONE:
    - GATEWAY
    - OZONE_DATANODE
    - OZONE_MANAGER
    - OZONE_RECON
    - S3_GATEWAY
    - STORAGE_CONTAINER_MANAGER
  PHOENIX:
    - PHOENIX_QUERY_SERVER
  QUEUEMANAGER:
    - QUEUEMANAGER_STORE
    - QUEUEMANAGER_WEBAPP
  RANGER:
    - RANGER_ADMIN
    - RANGER_TAGSYNC
    - RANGER_USERSYNC
  RANGER_KMS:
    - RANGER_KMS_SERVER
  RANGER_KMS_KTS:
    - RANGER_KMS_SERVER_KTS
  RANGER_RAZ:
    - RANGER_RAZ_SERVER
  SCHEMAREGISTRY:
    - GATEWAY
    - SCHEMA_REGISTRY_SERVER
  SOLR:
    - GATEWAY
    - SOLR_SERVER
  SPARK_ON_YARN:
    - GATEWAY
    - SPARK_YARN_HISTORY_SERVER
  SQOOP_CLIENT:
    - GATEWAY
  STREAMS_MESSAGING_MANAGER:
    - STREAMS_MESSAGING_MANAGER_UI
    - STREAMS_MESSAGING_MANAGER_SERVER
  STREAMS_REPLICATION_MANAGER:
    - GATEWAY
    - STREAMS_REPLICATION_MANAGER_DRIVER
    - STREAMS_REPLICATION_MANAGER_SERVICE
  TEZ:
    - GATEWAY
  THALES_KMS:
    - HSMKP_METASTORE_THALES
    - HSMKP_THALES
  YARN:
    - GATEWAY
    - JOBHISTORY
    - NODEMANAGER
    - RESOURCEMANAGER
  ZEPPELIN:
    - ZEPPELIN_SERVER
  ZOOKEEPER:
    - SERVER

