# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Include variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Install KRB5 server
  package:
    name: "{{ krb5_packages }}"
    state: present

- name: Set kdc.conf
  template:
    src: "{{ ansible_os_family }}/kdc.conf.j2"
    dest: "{{ krb5_kdc_state_directory }}/kdc.conf"
    backup: yes

- name: Create KDC database
  command: "/usr/sbin/kdb5_util create -s -P {{ krb5_kdc_master_password }}"
  args:
    creates: "{{ krb5_kdc_database }}"

- name: Set kadm5.acl
  template:
    src: kadm5.acl.j2
    dest: "{{ krb5_kdc_state_directory }}/kadm5.acl"
    backup: yes

- name: Create Cloudera Manager admin principal
  command: /usr/sbin/kadmin.local -q "addprinc -pw {{ krb5_kdc_admin_password }} {{ krb5_kdc_admin_user }}"

- name: Start Kerberos KDC
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ krb5_services }}"
