# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Work out temp and repo paths
  set_fact:
    temp_dir: "{{ local_temp_dir }}/{{ repo_tar_file | regex_replace('.tar.gz','') }}"
    repo_dir: /var/www/html/{{ repo_tar_file | regex_replace("-([0-9\.]+)-parcels.tar.gz", "/\1/parcels") }}

- name: Upload and extract parcel tar file
  unarchive:
    src: "{{ repo_tar_local_dir }}/{{ repo_tar_file }}"
    dest: "{{ local_temp_dir }}"

- name: Find parcel files
  find:
    path: "{{ temp_dir }}"
    patterns: '*.parcel,*.parcel.sha,*.parcel.sha1,.*.parcel.sha256,manifest.json'
    recurse: yes
  register: files

- name: Create parcel repo directory
  file:
    path: "{{ repo_dir }}"
    state: directory
    mode: 0755

- name: Copy parcel files into correct location
  copy:
    src: "{{ item.path }}"
    dest: "{{ repo_dir }}"
    remote_src: yes
    mode: 0644
  with_items: "{{ files.files }}"

- name: Remove temp directory
  file:
    path: "{{ temp_dir }}"
    state: absent
