---
# Copyright 2023 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Fail Fast if ECS OS is not RH family
  ansible.builtin.fail:
    msg: ECS is not supported on this OS, should be Centos or RHEL
  when: ansible_os_family != 'RedHat'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Install necessary additional packages
  ansible.builtin.package:
    name: "{{ __package_item }}"
    state: latest
  loop:
    - nfs-utils
    - iscsi-initiator-utils
  loop_control:
    loop_var: __package_item

- name: Setup iptables for rhel7
  when: ansible_distribution_major_version | int == 7
  block:
    - name: Install iptables for rhel7
      ansible.builtin.package:
        lock_timeout: 180
        name: "{{ __iptables_item }}"
        update_cache: true
        state: present
      loop:
        - iptables
      loop_control:
        loop_var: __iptables_item

- name: Setup iptables for rhel8
  when: ansible_distribution_major_version | int >= 8
  block:
    - name: Install iptables for rhel8, using rpm option tsflags=noscripts
      ansible.builtin.command: dnf install -y iptables --setopt=tsflags=noscripts

- name: Flush iptables
  ansible.builtin.iptables:
    flush: true
    table: "{{ __iptables_flush_item }}"
  loop:
    - filter
    - nat
    - mangle
    - raw
    - security
  loop_control:
    loop_var: __iptables_flush_item

## see https://docs.rke2.io/known_issues
- name: Set NetworkManager to ignore any ECS calico & flannel interfaces
  ansible.builtin.copy:
    src: networkmanager.conf
    dest: /etc/NetworkManager/conf.d/rke2-canal.config
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_distribution_major_version|int >= 7
    - ansible_facts.services["NetworkManager.service"]['status'] != "not-found"

- name: Reload NetworkManager daemon
  ansible.builtin.service:
    state: restarted
    daemon_reload: true
    name: NetworkManager.service
  when:
    - ansible_distribution_major_version|int >= 7
    - ansible_facts.services["NetworkManager.service"]['status'] != "not-found"
