# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Include variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Use Custom Repo as Archive Base if using Custom Repo
  when:
    - set_custom_repo_as_archive_base_url | bool
    - '"custom_repo" in groups'
  ansible.builtin.set_fact:
    cloudera_archive_base_url: "http://{{ groups['custom_repo'] | first }}"

- name: Correct repo URL for Redhat with cm5
  ansible.builtin.set_fact:
    __cloudera_manager_repo_url_paywall: "{{ cloudera_archive_base_url | regex_replace('/?$','') }}/p/cm{{ __cloudera_manager_major_version }}/redhat/{{ ansible_distribution_major_version }}/x86_64/cm/{{ cloudera_manager_version }}"
  when:
    - ansible_os_family != "Debian"
    - cloudera_manager_version.split('.')[0] == "5"

- name: Define Cloudera Manager trial repository details
  set_fact:
    cloudera_manager_repo_url: "{{ __cloudera_manager_repo_url_trial }}"
    cloudera_manager_repo_key: "{{ __cloudera_manager_repo_key_trial }}"
  when: cloudera_manager_repo_url is not defined and cloudera_manager_repo_username is not defined

- name: Define Cloudera Manager paywall repository details
  set_fact:
    cloudera_manager_repo_url: "{{ __cloudera_manager_repo_url_paywall }}"
    cloudera_manager_repo_key: "{{ __cloudera_manager_repo_key_paywall }}"
  when: cloudera_manager_repo_url is not defined and cloudera_manager_repo_username is defined

- name: Define Cloudera Manager repository key URL
  set_fact:
    cloudera_manager_repo_key: "{{ cloudera_manager_repo_url | regex_replace('/?$','') }}/{{ __cloudera_manager_repo_key_filename }}"
  when: cloudera_manager_repo_key is not defined

- name: Install Cloudera Manager repository
  when: install_repo_on_host
  include_tasks:
    file: "main-{{ ansible_os_family }}.yml"