# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
database_host: "{{ groups['db_server'][0] | default('localhost') }}"
database_type: postgresql
database_default_password: changeme
database_version: "{{ 10 if database_type == 'postgresql' else 10.2 }}"
database_tls: false

krb5_realm: CLOUDERA.LOCAL
krb5_kdc_admin_user: "cloudera-scm/admin@{{ krb5_realm }}"
krb5_kdc_admin_password: changeme
krb5_kdc_type: MIT KDC
krb5_enc_types: "aes256-cts aes128-cts"

manual_tls_cert_distribution: false
local_temp_dir: '/tmp'

database_defaults:
  ACTIVITYMONITOR:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: amon
    user: amon
    password: "{{ database_default_password }}"
  DAS:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: das
    user: das
    password: "{{ database_default_password }}"
  HIVE:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: metastore
    user: hive
    password: "{{ database_default_password }}"
  HUE:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: hue
    user: hue
    password: "{{ database_default_password }}"
  NAVIGATOR:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: nav
    user: nav
    password: "{{ database_default_password }}"
  NAVIGATORMETASERVER:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: navms
    user: navms
    password: "{{ database_default_password }}"
  OOZIE:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: oozie
    user: oozie
    password: "{{ database_default_password }}"
  RANGER:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: ranger
    user: rangeradmin
    password: "{{ database_default_password }}"
  REPORTSMANAGER:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: rman
    user: rman
    password: "{{ database_default_password }}"
  SCHEMAREGISTRY:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: schemaregistry
    user: schemaregistry
    password: "{{ database_default_password }}"
  STREAMS_MESSAGING_MANAGER:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: streamsmsgmgr
    user: streamsmsgmgr
    password: "{{ database_default_password }}"
  SENTRY:
    host: "{{ database_host }}"
    port: "{{ database_port | cloudera.cluster.default_database_port }}"
    type: "{{ database_type }}"
    name: sentry
    user: sentry
    password: "{{ database_default_password }}"
