# Copyright 2023 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

#- name: Include config cluster defaults for deployment
#  ansible.builtin.include_role:
#    name: cloudera.cluster.config.cluster.base
#    public: yes

#- name: Include config cluster ecs defaults for deployment
#  ansible.builtin.include_role:
#    name: cloudera.cluster.config.cluster.ecs
#    public: yes

- name: Ensure properly configured
  assert:
    that: >-
      {{
        (teardown_everything is defined and teardown_everything)
        or teardown_cluster is defined
        or (teardown_skip_cluster_deletion is defined and teardown_skip_cluster_deletion)
      }}
    success_msg: "Teardown is properly configured and will execute"
    fail_msg: >-
      Please set teardown_everything to true to teardown
      every cluster and cm.
      Alternatively, specify a cluster
      to teardown using teardown_cluster ('all' to teardown
      every cluster).
      You can also set teardown_skip_cluster_deletion to true
      to skip cluster deletion in CM.

- name: Stop ECS CLuster
  include_role:
    name: cloudera.cluster.operations.stop_cluster
  run_once: true

- name: Run rke2 killall
  register: _rke2_killall
  shell: /opt/cloudera/parcels/ECS/bin/rke2-killall.sh
  failed_when:
    - _rke2_killall.failed
    - "'No such file or directory' not in _rke2_killall.stderr"

#TODO emove all remaing kubelet or k3s mounts, address global ro mounts left over from nfs
- name: Remove all remaing kubelet or k3s mounts
  shell: mount | awk '/on \/var\/lib\/(kubelet|k3s)/{print \$3}' | xargs -r sudo umount -l"

- name: Run rke2 Uninstall
  register: _rke2_uninstall
  shell: /opt/cloudera/parcels/ECS/bin/rke2-uninstall.sh;
  failed_when:
    - _rke2_uninstall.failed
    - "'No such file or directory' not in _rke2_uninstall.stderr"

- name: Delete misc
  shell: |
    rm -rf /mnt/docker/*
    rm -rf /mnt/ecs/local-storage/*
    rm -rf /mnt2/ecs/longhorn-storage/*
    rm -rf /var/lib/docker_server
    rm -rf /etc/docker/certs.d
    rm -rf /var/lib/ecs
    systemctl stop iscsid
    yum -y erase iscsi-initiator-utils
    rm -rf /var/lib/iscsi
    rm -rf /etc/iscsi
    rm -rf /etc/cni
    rm -f /run/longhorn-iscsi.lock
    rm -rf /run/k3s
    rm -rf /run/containerd
    rm -rf /var/lib/docker/*
    rm -rf /var/log/containers/*
    rm -rf /var/log/pods/*
  ignore_errors: true


- name: Flush and Delete IPTables
  ansible.builtin.iptables:
    flush: yes
    table: "{{ __iptables_flush_item }}"
  loop:
    - filter
    - nat
    - mangle
    - raw
    - security
  loop_control:
    loop_var: __iptables_flush_item

- name: Delete ECS CLuster
  include_role:
    name: cloudera.cluster.operations.delete_cluster
  run_once: true
